defmodule Jido.Console.Session.Protocol.Generated do
  @moduledoc """
  Generated protocol types for `jido.session` v1.

  Do not edit this file. Run `mix jido.protocol.generate`.
  """

  @digest "9ea4e0fa7924f0da811d2adc008cb0468840fee80564280cecb8fbd6ad186bee"
  @catalog %{
    "authority" => %{
      "authority_fields" => ["permission", "approval", "capability", "principal", "scope"],
      "descriptive_only" => ["origin", "host", "transport", "renderer"],
      "never_grant_from" => ["renderer", "transport", "host", "origin", "unknown"]
    },
    "bounds" => %{
      "max_attachments" => 20,
      "max_identity_bytes" => 256,
      "max_list_items" => 1000,
      "max_map_keys" => 128,
      "max_snapshot_bytes" => 1_048_576,
      "max_string_bytes" => 65536,
      "max_text_bytes" => 200_000,
      "max_unknown_bytes" => 4096,
      "max_unknown_keys" => 16
    },
    "client_local_fields" => [
      "draft",
      "cursor",
      "viewport",
      "terminal_size",
      "ansi",
      "dom",
      "navigation",
      "key_chord",
      "palette",
      "selection_anchor"
    ],
    "digest" => "9ea4e0fa7924f0da811d2adc008cb0468840fee80564280cecb8fbd6ad186bee",
    "families" => %{
      "command" => %{
        "compatibility" => "additive",
        "types" => %{
          "acknowledge" => %{"fields" => ["client_id", "sequence"], "locality" => "shared"},
          "consume_queued" => %{"fields" => ["input_id", "client_id", "queue"], "locality" => "shared"},
          "invoke_command" => %{"fields" => ["command_id", "client_id", "name", "arguments"], "locality" => "shared"},
          "queue_follow_up" => %{"fields" => ["input_id", "client_id", "text"], "locality" => "shared"},
          "remove_queued" => %{"fields" => ["input_id", "client_id", "queue"], "locality" => "shared"},
          "request_replay" => %{"fields" => ["client_id", "after_sequence"], "locality" => "shared"},
          "request_snapshot" => %{"fields" => ["client_id"], "locality" => "shared"},
          "steer" => %{"fields" => ["input_id", "client_id", "run_id", "text"], "locality" => "shared"},
          "submit_input" => %{"fields" => ["input_id", "client_id", "text", "attachments"], "locality" => "shared"}
        },
        "version" => "1"
      },
      "control" => %{
        "compatibility" => "additive",
        "types" => %{
          "attach" => %{"fields" => ["client_id", "attachment_id", "capabilities"], "locality" => "shared"},
          "cancel" => %{"fields" => ["control_id", "run_id", "request_id", "worker_id"], "locality" => "shared"},
          "detach" => %{"fields" => ["client_id", "attachment_id"], "locality" => "shared"},
          "drain" => %{"fields" => ["control_id", "run_id"], "locality" => "shared"},
          "force_kill" => %{"fields" => ["control_id", "run_id", "request_id", "worker_id"], "locality" => "shared"},
          "recover" => %{"fields" => ["client_id", "last_acknowledged"], "locality" => "shared"}
        },
        "version" => "1"
      },
      "event" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_attached" => %{"fields" => ["client_id", "attachment_id"], "locality" => "shared"},
          "client_detached" => %{"fields" => ["client_id", "attachment_id"], "locality" => "shared"},
          "command_effected" => %{"fields" => ["command_id", "effect"], "locality" => "shared"},
          "control_completed" => %{"fields" => ["control_id", "result"], "locality" => "shared"},
          "control_requested" => %{"fields" => ["control_id", "control"], "locality" => "shared"},
          "delivery_gap" => %{
            "fields" => ["client_id", "last_acknowledged", "current_sequence"],
            "locality" => "shared"
          },
          "input_admitted" => %{"fields" => ["input_id", "client_id"], "locality" => "shared"},
          "input_cancelled" => %{"fields" => ["input_id", "reason"], "locality" => "shared"},
          "input_completed" => %{"fields" => ["input_id", "run_id"], "locality" => "shared"},
          "input_rejected" => %{"fields" => ["input_id", "reason"], "locality" => "shared"},
          "input_started" => %{"fields" => ["input_id", "run_id"], "locality" => "shared"},
          "model_completed" => %{"fields" => ["run_id", "content"], "locality" => "shared"},
          "model_delta" => %{"fields" => ["run_id", "text"], "locality" => "shared"},
          "permission_decided" => %{"fields" => ["approval_id", "decision"], "locality" => "shared"},
          "permission_requested" => %{"fields" => ["approval_id", "principal", "scope"], "locality" => "shared"},
          "queue_changed" => %{"fields" => ["queue", "items"], "locality" => "shared"},
          "run_completed" => %{"fields" => ["run_id", "outcome_id"], "locality" => "shared"},
          "run_failed" => %{"fields" => ["run_id", "reason"], "locality" => "shared"},
          "run_progress" => %{"fields" => ["run_id", "summary"], "locality" => "shared"},
          "run_started" => %{"fields" => ["run_id", "turn_id"], "locality" => "shared"},
          "session_failed" => %{"fields" => ["reason"], "locality" => "shared"},
          "tool_completed" => %{"fields" => ["run_id", "step_id", "content"], "locality" => "shared"},
          "tool_failed" => %{"fields" => ["run_id", "step_id", "reason"], "locality" => "shared"},
          "tool_started" => %{"fields" => ["run_id", "step_id", "operation"], "locality" => "shared"},
          "worker_completed" => %{"fields" => ["worker_id", "run_id", "request_id"], "locality" => "shared"},
          "worker_failed" => %{"fields" => ["worker_id", "run_id", "reason"], "locality" => "shared"},
          "worker_started" => %{"fields" => ["worker_id", "run_id", "request_id"], "locality" => "shared"}
        },
        "version" => "1"
      },
      "interaction" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_ack" => %{"fields" => ["client_id", "sequence"], "locality" => "shared"},
          "cursor_moved" => %{"fields" => ["cursor"], "locality" => "client_local"},
          "draft_changed" => %{"fields" => ["draft"], "locality" => "client_local"},
          "key_local" => %{"fields" => ["key_chord"], "locality" => "client_local"},
          "permission_response" => %{"fields" => ["client_id", "approval_id", "decision"], "locality" => "shared"},
          "slash_command" => %{"fields" => ["client_id", "name", "arguments"], "locality" => "shared"},
          "user_steer" => %{"fields" => ["client_id", "run_id", "text"], "locality" => "shared"},
          "user_text" => %{"fields" => ["client_id", "text"], "locality" => "shared"},
          "viewport_changed" => %{"fields" => ["viewport"], "locality" => "client_local"}
        },
        "version" => "1"
      },
      "outcome" => %{
        "compatibility" => "additive",
        "types" => %{
          "approved" => %{"fields" => ["approval_id", "scope"], "locality" => "shared"},
          "cancelled" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"},
          "completed" => %{"fields" => ["ref_id", "content", "view"], "locality" => "shared"},
          "denied" => %{"fields" => ["approval_id", "scope"], "locality" => "shared"},
          "expired" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"},
          "failed" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"},
          "no_effect" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"}
        },
        "version" => "1"
      },
      "replay" => %{
        "compatibility" => "additive",
        "types" => %{
          "event_suffix" => %{"fields" => ["after_sequence", "events"], "locality" => "shared"},
          "replay_request" => %{"fields" => ["client_id", "after_sequence"], "locality" => "shared"}
        },
        "version" => "1"
      },
      "response" => %{
        "compatibility" => "additive",
        "types" => %{
          "accepted" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"},
          "deferred" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"},
          "rejected" => %{"fields" => ["ref_id", "reason"], "locality" => "shared"}
        },
        "version" => "1"
      },
      "snapshot" => %{
        "compatibility" => "additive",
        "types" => %{
          "session_snapshot" => %{"fields" => ["sequence", "state", "protocol_version"], "locality" => "shared"}
        },
        "version" => "1"
      }
    },
    "protocol" => "jido.session",
    "version" => "1"
  }

  @doc "Returns the schema digest this file was generated from."
  @spec digest() :: String.t()
  def digest, do: @digest

  @doc "Returns the generated protocol catalog."
  @spec catalog() :: map()
  def catalog, do: @catalog

  @doc "Returns generated family names."
  @spec families() :: [String.t()]
  def families, do: Map.keys(@catalog["families"]) |> Enum.sort()

  @doc "Returns generated type names for one family."
  @spec types(String.t()) :: [String.t()]
  def types(family) when is_binary(family) do
    @catalog
    |> get_in(["families", family, "types"])
    |> List.wrap()
    |> then(fn
      [types] when is_map(types) -> Map.keys(types) |> Enum.sort()
      _other -> []
    end)
  end
end
