defmodule Jido.Console.Session.Protocol.Generated do
  @moduledoc """
  Generated protocol types for `jido.session` v1.

  Do not edit this file. Run `mix jido.protocol.generate`.
  """

  @digest "6b693fba12ed661ef606d2078f82c339255dbc89cf1c6e7b610d641161d6c949"
  @catalog %{
    "authority" => %{
      "authority_fields" => ["permission", "approval", "capability", "principal", "scope"],
      "descriptive_only" => ["origin", "host", "transport", "renderer"],
      "never_grant_from" => ["renderer", "transport", "host", "origin", "unknown"]
    },
    "bounds" => %{
      "max_attachments" => 20,
      "max_identity_bytes" => 256,
      "max_list_items" => 1000,
      "max_map_keys" => 128,
      "max_snapshot_bytes" => 1_048_576,
      "max_string_bytes" => 65536,
      "max_text_bytes" => 200_000,
      "max_unknown_bytes" => 4096,
      "max_unknown_keys" => 16
    },
    "client_local_fields" => [
      "draft",
      "cursor",
      "viewport",
      "terminal_size",
      "ansi",
      "dom",
      "navigation",
      "key_chord",
      "palette",
      "selection_anchor"
    ],
    "digest" => "6b693fba12ed661ef606d2078f82c339255dbc89cf1c6e7b610d641161d6c949",
    "families" => %{
      "command" => %{
        "compatibility" => "additive",
        "types" => %{
          "acknowledge" => %{
            "known_fields" => ["client_id", "sequence"],
            "locality" => "shared",
            "required_fields" => []
          },
          "consume_queued" => %{
            "known_fields" => ["client_id", "input_id", "queue"],
            "locality" => "shared",
            "required_fields" => []
          },
          "invoke_command" => %{
            "known_fields" => ["arguments", "client_id", "command_id", "name"],
            "locality" => "shared",
            "required_fields" => []
          },
          "queue_follow_up" => %{
            "known_fields" => ["client_id", "input_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "remove_queued" => %{
            "known_fields" => ["client_id", "input_id", "queue"],
            "locality" => "shared",
            "required_fields" => []
          },
          "request_replay" => %{
            "known_fields" => ["after_sequence", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "request_snapshot" => %{
            "known_fields" => ["client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "steer" => %{
            "known_fields" => ["client_id", "input_id", "run_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "submit_input" => %{
            "known_fields" => ["attachments", "client_id", "input_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "control" => %{
        "compatibility" => "additive",
        "types" => %{
          "attach" => %{
            "known_fields" => ["attachment_id", "capabilities", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "cancel" => %{
            "known_fields" => ["control_id", "request_id", "run_id", "worker_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "detach" => %{
            "known_fields" => ["attachment_id", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "drain" => %{
            "known_fields" => ["control_id", "run_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "force_kill" => %{
            "known_fields" => ["control_id", "request_id", "run_id", "worker_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "recover" => %{
            "known_fields" => ["client_id", "last_acknowledged"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "delivery" => %{
        "compatibility" => "additive",
        "types" => %{
          "attach_snapshot" => %{
            "known_fields" => ["attachment_id", "client_id", "snapshot", "snapshot_sequence"],
            "locality" => "shared",
            "required_fields" => ["attachment_id", "client_id", "snapshot", "snapshot_sequence"]
          },
          "gap" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "current_owner_sequence",
              "gap_id",
              "last_acknowledged_sequence",
              "reason"
            ],
            "locality" => "shared",
            "required_fields" => [
              "attachment_id",
              "client_id",
              "current_owner_sequence",
              "gap_id",
              "last_acknowledged_sequence",
              "reason"
            ]
          },
          "output_batch" => %{
            "known_fields" => [
              "acknowledgement_token",
              "attachment_id",
              "batch_id",
              "client_id",
              "events",
              "first_sequence",
              "through_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "acknowledgement_token",
              "attachment_id",
              "batch_id",
              "client_id",
              "events",
              "first_sequence",
              "through_sequence"
            ]
          },
          "recovery_receipt" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "process_lifetime",
              "recovery_id",
              "through_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "attachment_id",
              "client_id",
              "process_lifetime",
              "recovery_id",
              "through_sequence"
            ]
          },
          "recovery_snapshot" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "snapshot",
              "snapshot_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "attachment_id",
              "client_id",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "snapshot",
              "snapshot_sequence"
            ]
          },
          "recovery_suffix" => %{
            "known_fields" => [
              "after_sequence",
              "attachment_id",
              "client_id",
              "completion_token",
              "events",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "through_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "after_sequence",
              "attachment_id",
              "client_id",
              "completion_token",
              "events",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "through_sequence"
            ]
          }
        },
        "version" => "1"
      },
      "event" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_attached" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "client_detached" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "command_effected" => %{
            "known_fields" => [
              "command_id",
              "durability",
              "effect",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "control_completed" => %{
            "known_fields" => [
              "control_id",
              "durability",
              "identities",
              "origin",
              "result",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "control_requested" => %{
            "known_fields" => [
              "control",
              "control_id",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "delivery_gap" => %{
            "deprecated" => true,
            "emission" => "input_only",
            "known_fields" => [
              "client_id",
              "current_sequence",
              "durability",
              "identities",
              "last_acknowledged",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_admitted" => %{
            "known_fields" => [
              "client_id",
              "durability",
              "identities",
              "input_id",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_cancelled" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "reason",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_completed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_rejected" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "reason",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "model_completed" => %{
            "known_fields" => [
              "content",
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "model_delta" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "text",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "permission_decided" => %{
            "known_fields" => [
              "approval_id",
              "decision",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "permission_requested" => %{
            "known_fields" => [
              "approval_id",
              "durability",
              "identities",
              "origin",
              "principal",
              "scope",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "queue_changed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "items",
              "origin",
              "queue",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_completed" => %{
            "known_fields" => [
              "content",
              "durability",
              "identities",
              "origin",
              "outcome_id",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_progress" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "summary",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "turn_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "session_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "tool_completed" => %{
            "known_fields" => [
              "content",
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "step_id",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "tool_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "run_id",
              "sensitivity",
              "sequence",
              "step_id",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "tool_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "operation",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "step_id",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "worker_completed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "request_id",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "worker_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "worker_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "worker_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "worker_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "request_id",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "worker_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          }
        },
        "version" => "1"
      },
      "interaction" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_ack" => %{
            "known_fields" => ["client_id", "sequence"],
            "locality" => "shared",
            "required_fields" => []
          },
          "cursor_moved" => %{
            "known_fields" => ["cursor"],
            "locality" => "client_local",
            "required_fields" => []
          },
          "draft_changed" => %{
            "known_fields" => ["draft"],
            "locality" => "client_local",
            "required_fields" => []
          },
          "key_local" => %{
            "known_fields" => ["key_chord"],
            "locality" => "client_local",
            "required_fields" => []
          },
          "permission_response" => %{
            "known_fields" => ["approval_id", "client_id", "decision"],
            "locality" => "shared",
            "required_fields" => []
          },
          "slash_command" => %{
            "known_fields" => ["arguments", "client_id", "name"],
            "locality" => "shared",
            "required_fields" => []
          },
          "user_steer" => %{
            "known_fields" => ["client_id", "run_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "user_text" => %{
            "known_fields" => ["client_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "viewport_changed" => %{
            "known_fields" => ["viewport"],
            "locality" => "client_local",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "outcome" => %{
        "compatibility" => "additive",
        "types" => %{
          "approved" => %{
            "known_fields" => ["approval_id", "scope"],
            "locality" => "shared",
            "required_fields" => []
          },
          "cancelled" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "completed" => %{
            "known_fields" => ["content", "ref_id", "view"],
            "locality" => "shared",
            "required_fields" => []
          },
          "denied" => %{
            "known_fields" => ["approval_id", "scope"],
            "locality" => "shared",
            "required_fields" => []
          },
          "expired" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "failed" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "no_effect" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "replay" => %{
        "compatibility" => "additive",
        "types" => %{
          "event_suffix" => %{
            "known_fields" => ["after_sequence", "events"],
            "locality" => "shared",
            "required_fields" => []
          },
          "replay_request" => %{
            "known_fields" => ["after_sequence", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "response" => %{
        "compatibility" => "additive",
        "types" => %{
          "accepted" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "deferred" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "rejected" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "snapshot" => %{
        "compatibility" => "additive",
        "types" => %{
          "session_snapshot" => %{
            "known_fields" => ["protocol_version", "sequence", "state"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      }
    },
    "protocol" => "jido.session",
    "version" => "1"
  }

  @doc "Returns the schema digest this file was generated from."
  @spec digest() :: String.t()
  def digest, do: @digest

  @doc "Returns the generated protocol catalog."
  @spec catalog() :: map()
  def catalog, do: @catalog

  @doc "Returns generated family names."
  @spec families() :: [String.t()]
  def families, do: Map.keys(@catalog["families"]) |> Enum.sort()

  @doc "Returns generated type names for one family."
  @spec types(String.t()) :: [String.t()]
  def types(family) when is_binary(family) do
    @catalog
    |> get_in(["families", family, "types"])
    |> List.wrap()
    |> then(fn
      [types] when is_map(types) -> Map.keys(types) |> Enum.sort()
      _other -> []
    end)
  end
end
