defmodule Jido.Console.Session.Protocol.Generated do
  @moduledoc """
  Generated protocol types for `jido.session` v1.

  Do not edit this file. Run `mix jido.protocol.generate`.
  """

  @digest "e167507c61a1ada7ed2934e41caa3bf023a592ccbe063ab90a75dec8549e40e2"
  @catalog %{
    "authority" => %{
      "authority_fields" => ["permission", "approval", "capability", "principal", "scope"],
      "descriptive_only" => ["origin", "host", "transport", "renderer"],
      "never_grant_from" => ["renderer", "transport", "host", "origin", "unknown"]
    },
    "bounds" => %{
      "max_attachments" => 20,
      "max_identity_bytes" => 256,
      "max_list_items" => 1000,
      "max_map_keys" => 128,
      "max_snapshot_bytes" => 1_048_576,
      "max_string_bytes" => 65536,
      "max_text_bytes" => 200_000,
      "max_unknown_bytes" => 4096,
      "max_unknown_keys" => 16
    },
    "client_local_fields" => [
      "draft",
      "cursor",
      "viewport",
      "terminal_size",
      "ansi",
      "dom",
      "navigation",
      "key_chord",
      "palette",
      "selection_anchor"
    ],
    "digest" => "e167507c61a1ada7ed2934e41caa3bf023a592ccbe063ab90a75dec8549e40e2",
    "families" => %{
      "command" => %{
        "compatibility" => "additive",
        "types" => %{
          "acknowledge" => %{
            "known_fields" => ["client_id", "sequence"],
            "locality" => "shared",
            "required_fields" => []
          },
          "consume_queued" => %{
            "known_fields" => ["client_id", "input_id", "queue"],
            "locality" => "shared",
            "required_fields" => []
          },
          "invoke_command" => %{
            "known_fields" => ["arguments", "client_id", "command_id", "name"],
            "locality" => "shared",
            "required_fields" => []
          },
          "queue_follow_up" => %{
            "known_fields" => ["client_id", "input_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "remove_queued" => %{
            "known_fields" => ["client_id", "input_id", "queue"],
            "locality" => "shared",
            "required_fields" => []
          },
          "request_replay" => %{
            "known_fields" => ["after_sequence", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "request_snapshot" => %{
            "known_fields" => ["client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "steer" => %{
            "known_fields" => ["client_id", "input_id", "run_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "submit_input" => %{
            "known_fields" => ["attachments", "client_id", "input_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "control" => %{
        "compatibility" => "additive",
        "types" => %{
          "attach" => %{
            "known_fields" => ["attachment_id", "capabilities", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "cancel" => %{
            "known_fields" => ["control_id", "request_id", "run_id", "worker_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "detach" => %{
            "known_fields" => ["attachment_id", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "drain" => %{
            "known_fields" => ["control_id", "run_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "force_kill" => %{
            "known_fields" => ["control_id", "request_id", "run_id", "worker_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "recover" => %{
            "known_fields" => ["client_id", "last_acknowledged"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "delivery" => %{
        "compatibility" => "additive",
        "types" => %{
          "attach_snapshot" => %{
            "known_fields" => ["attachment_id", "client_id", "snapshot", "snapshot_sequence"],
            "locality" => "shared",
            "required_fields" => ["attachment_id", "client_id", "snapshot", "snapshot_sequence"]
          },
          "gap" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "current_owner_sequence",
              "gap_id",
              "last_acknowledged_sequence",
              "reason"
            ],
            "locality" => "shared",
            "required_fields" => [
              "attachment_id",
              "client_id",
              "current_owner_sequence",
              "gap_id",
              "last_acknowledged_sequence",
              "reason"
            ]
          },
          "output_batch" => %{
            "known_fields" => [
              "acknowledgement_token",
              "attachment_id",
              "batch_id",
              "client_id",
              "events",
              "first_sequence",
              "through_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "acknowledgement_token",
              "attachment_id",
              "batch_id",
              "client_id",
              "events",
              "first_sequence",
              "through_sequence"
            ]
          },
          "recovery_receipt" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "process_lifetime",
              "recovery_id",
              "through_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "attachment_id",
              "client_id",
              "process_lifetime",
              "recovery_id",
              "through_sequence"
            ]
          },
          "recovery_snapshot" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "snapshot",
              "snapshot_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "attachment_id",
              "client_id",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "snapshot",
              "snapshot_sequence"
            ]
          },
          "recovery_suffix" => %{
            "known_fields" => [
              "after_sequence",
              "attachment_id",
              "client_id",
              "completion_token",
              "events",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "through_sequence"
            ],
            "locality" => "shared",
            "required_fields" => [
              "after_sequence",
              "attachment_id",
              "client_id",
              "completion_token",
              "events",
              "gap_id",
              "recovery_id",
              "recovery_token",
              "through_sequence"
            ]
          }
        },
        "version" => "1"
      },
      "event" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_attached" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "client_detached" => %{
            "known_fields" => [
              "attachment_id",
              "client_id",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "command_effected" => %{
            "known_fields" => [
              "command_id",
              "durability",
              "effect",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "control_completed" => %{
            "known_fields" => [
              "control_id",
              "durability",
              "identities",
              "origin",
              "result",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "control_requested" => %{
            "known_fields" => [
              "control",
              "control_id",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "delivery_gap" => %{
            "deprecated" => true,
            "emission" => "input_only",
            "known_fields" => [
              "client_id",
              "current_sequence",
              "durability",
              "identities",
              "last_acknowledged",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_admitted" => %{
            "known_fields" => [
              "client_id",
              "durability",
              "identities",
              "input_id",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_cancelled" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "reason",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_completed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_rejected" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "reason",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "input_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "input_id",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "model_completed" => %{
            "known_fields" => [
              "content",
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "model_delta" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "text",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "permission_decided" => %{
            "known_fields" => [
              "approval_id",
              "decision",
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "permission_requested" => %{
            "known_fields" => [
              "approval_id",
              "durability",
              "identities",
              "origin",
              "principal",
              "scope",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "queue_changed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "items",
              "origin",
              "queue",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_completed" => %{
            "known_fields" => [
              "content",
              "durability",
              "identities",
              "origin",
              "outcome_id",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "run_id",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_progress" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "summary",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "run_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "turn_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "session_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "sensitivity",
              "sequence",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "tool_completed" => %{
            "known_fields" => [
              "content",
              "durability",
              "identities",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "step_id",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "tool_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "run_id",
              "sensitivity",
              "sequence",
              "step_id",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "tool_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "operation",
              "origin",
              "run_id",
              "sensitivity",
              "sequence",
              "step_id",
              "trust"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "worker_completed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "request_id",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "worker_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "worker_failed" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "reason",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "worker_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          },
          "worker_started" => %{
            "known_fields" => [
              "durability",
              "identities",
              "origin",
              "request_id",
              "run_id",
              "sensitivity",
              "sequence",
              "trust",
              "worker_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "durability",
              "identities",
              "origin",
              "sensitivity",
              "sequence",
              "trust"
            ]
          }
        },
        "version" => "1"
      },
      "generation" => %{
        "compatibility" => "additive",
        "types" => %{
          "claim" => %{
            "field_values" => %{"status" => ["claimed", "conflict", "timeout_unknown"]},
            "known_fields" => [
              "generation",
              "operation_id",
              "owner_instance_id",
              "prior_generation",
              "status"
            ],
            "locality" => "shared",
            "required_fields" => [
              "generation",
              "operation_id",
              "owner_instance_id",
              "prior_generation",
              "status"
            ]
          },
          "fenced_operation" => %{
            "field_values" => %{"status" => ["accepted", "stale_generation", "wrong_owner"]},
            "known_fields" => ["generation", "operation_id", "owner_instance_id", "status"],
            "locality" => "shared",
            "required_fields" => ["generation", "operation_id", "owner_instance_id", "status"]
          }
        },
        "version" => "1"
      },
      "interaction" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_ack" => %{
            "known_fields" => ["client_id", "sequence"],
            "locality" => "shared",
            "required_fields" => []
          },
          "cursor_moved" => %{
            "known_fields" => ["cursor"],
            "locality" => "client_local",
            "required_fields" => []
          },
          "draft_changed" => %{
            "known_fields" => ["draft"],
            "locality" => "client_local",
            "required_fields" => []
          },
          "key_local" => %{
            "known_fields" => ["key_chord"],
            "locality" => "client_local",
            "required_fields" => []
          },
          "permission_response" => %{
            "known_fields" => ["approval_id", "client_id", "decision"],
            "locality" => "shared",
            "required_fields" => []
          },
          "slash_command" => %{
            "known_fields" => ["arguments", "client_id", "name"],
            "locality" => "shared",
            "required_fields" => []
          },
          "user_steer" => %{
            "known_fields" => ["client_id", "run_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "user_text" => %{
            "known_fields" => ["client_id", "text"],
            "locality" => "shared",
            "required_fields" => []
          },
          "viewport_changed" => %{
            "known_fields" => ["viewport"],
            "locality" => "client_local",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "operation" => %{
        "compatibility" => "additive",
        "types" => %{
          "abandon" => %{
            "field_values" => %{
              "calls_model_or_tool" => [false],
              "mode" => ["abandon"],
              "status" => ["abandoned", "rejected", "timeout_unknown"],
              "watermark_required" => ["no"]
            },
            "known_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "decision_id",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ],
            "locality" => "shared",
            "required_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "decision_id",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ]
          },
          "exact_resume" => %{
            "field_values" => %{
              "calls_model_or_tool" => [false],
              "mode" => ["exact"],
              "status" => ["ready_exact", "rejected"],
              "watermark_required" => ["yes"]
            },
            "known_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "generation",
              "mode",
              "operation_id",
              "status",
              "watermark_id",
              "watermark_required"
            ],
            "locality" => "shared",
            "required_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ]
          },
          "fork" => %{
            "field_values" => %{
              "calls_model_or_tool" => [false],
              "mode" => ["exact_fork", "transcript_only_fork"],
              "status" => ["forked", "rejected", "timeout_unknown"],
              "watermark_required" => ["yes", "no"]
            },
            "known_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "child_session_id",
              "mode",
              "operation_id",
              "parent_boundary",
              "status",
              "watermark_required"
            ],
            "locality" => "shared",
            "required_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "child_session_id",
              "mode",
              "operation_id",
              "parent_boundary",
              "status",
              "watermark_required"
            ]
          },
          "repair" => %{
            "field_values" => %{
              "calls_model_or_tool" => [false],
              "mode" => ["repair"],
              "status" => ["planned", "completed", "rejected", "timeout_unknown"],
              "watermark_required" => ["depends_on_case"]
            },
            "known_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "decision_id",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ],
            "locality" => "shared",
            "required_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "decision_id",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ]
          },
          "retry" => %{
            "field_values" => %{
              "calls_model_or_tool" => [true],
              "mode" => ["retry"],
              "status" => ["reserved", "rejected", "timeout_unknown"],
              "watermark_required" => ["no"]
            },
            "known_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "mode",
              "new_request_id",
              "new_result_id",
              "operation_id",
              "status",
              "watermark_required"
            ],
            "locality" => "shared",
            "required_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "mode",
              "new_request_id",
              "new_result_id",
              "operation_id",
              "status",
              "watermark_required"
            ]
          },
          "transcript_only_resume" => %{
            "field_values" => %{
              "calls_model_or_tool" => [false],
              "mode" => ["transcript_only"],
              "status" => ["ready_transcript_only", "rejected"],
              "watermark_required" => ["no"]
            },
            "known_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "last_verified_watermark_id",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ],
            "locality" => "shared",
            "required_fields" => [
              "authority_rule",
              "calls_model_or_tool",
              "mode",
              "operation_id",
              "status",
              "watermark_required"
            ]
          }
        },
        "version" => "1"
      },
      "outcome" => %{
        "compatibility" => "additive",
        "types" => %{
          "approved" => %{
            "known_fields" => ["approval_id", "scope"],
            "locality" => "shared",
            "required_fields" => []
          },
          "cancelled" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "completed" => %{
            "known_fields" => ["content", "ref_id", "view"],
            "locality" => "shared",
            "required_fields" => []
          },
          "denied" => %{
            "known_fields" => ["approval_id", "scope"],
            "locality" => "shared",
            "required_fields" => []
          },
          "expired" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "failed" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "no_effect" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "receipt" => %{
        "compatibility" => "additive",
        "types" => %{
          "client_output" => %{
            "field_values" => %{
              "commit_boundary" => ["live_attachment_apply"],
              "durability" => ["process"],
              "status" => ["applied"]
            },
            "known_fields" => [
              "attachment_id",
              "commit_boundary",
              "durability",
              "status",
              "through_sequence"
            ],
            "locality" => "client_local",
            "required_fields" => [
              "attachment_id",
              "commit_boundary",
              "durability",
              "status",
              "through_sequence"
            ]
          },
          "command" => %{
            "field_values" => %{
              "commit_boundary" => ["sqlite_full_commit"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"]
            },
            "known_fields" => [
              "commit_boundary",
              "durability",
              "effective_arguments",
              "idempotency_key",
              "operation_id",
              "payload_digest",
              "result_id",
              "sequence",
              "status"
            ],
            "locality" => "shared",
            "required_fields" => [
              "commit_boundary",
              "durability",
              "effective_arguments",
              "idempotency_key",
              "operation_id",
              "payload_digest",
              "result_id",
              "sequence",
              "status"
            ]
          },
          "console_event" => %{
            "field_values" => %{
              "commit_boundary" => ["sqlite_full_commit"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"]
            },
            "known_fields" => [
              "chain_digest",
              "commit_boundary",
              "durability",
              "event_id",
              "operation_id",
              "sequence",
              "status"
            ],
            "locality" => "shared",
            "required_fields" => [
              "chain_digest",
              "commit_boundary",
              "durability",
              "event_id",
              "operation_id",
              "sequence",
              "status"
            ]
          },
          "effect_result" => %{
            "field_values" => %{
              "commit_boundary" => ["jidoka_store_transition"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"]
            },
            "known_fields" => [
              "commit_boundary",
              "durability",
              "jidoka_revision",
              "operation_id",
              "result_id",
              "result_status",
              "status"
            ],
            "locality" => "shared",
            "required_fields" => [
              "commit_boundary",
              "durability",
              "jidoka_revision",
              "operation_id",
              "result_id",
              "result_status",
              "status"
            ]
          },
          "effect_start" => %{
            "field_values" => %{
              "commit_boundary" => ["sqlite_full_commit"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"]
            },
            "known_fields" => [
              "approval_id",
              "arguments_digest",
              "commit_boundary",
              "durability",
              "operation_id",
              "replay_rule",
              "result_id",
              "safety_class",
              "status"
            ],
            "locality" => "shared",
            "required_fields" => [
              "approval_id",
              "arguments_digest",
              "commit_boundary",
              "durability",
              "operation_id",
              "replay_rule",
              "result_id",
              "safety_class",
              "status"
            ]
          },
          "input" => %{
            "field_values" => %{
              "commit_boundary" => ["sqlite_full_commit"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"]
            },
            "known_fields" => [
              "commit_boundary",
              "durability",
              "idempotency_key",
              "operation_id",
              "payload_digest",
              "sequence",
              "status"
            ],
            "locality" => "shared",
            "required_fields" => [
              "commit_boundary",
              "durability",
              "idempotency_key",
              "operation_id",
              "payload_digest",
              "sequence",
              "status"
            ]
          },
          "jidoka_checkpoint" => %{
            "field_values" => %{
              "commit_boundary" => ["jidoka_store_transition"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"]
            },
            "known_fields" => [
              "commit_boundary",
              "durability",
              "jidoka_revision",
              "jidoka_session_id",
              "operation_id",
              "snapshot_id",
              "status",
              "value_digest"
            ],
            "locality" => "shared",
            "required_fields" => [
              "commit_boundary",
              "durability",
              "jidoka_revision",
              "jidoka_session_id",
              "operation_id",
              "snapshot_id",
              "status",
              "value_digest"
            ]
          },
          "watermark" => %{
            "field_values" => %{
              "commit_boundary" => ["verified_watermark_commit"],
              "durability" => ["durable"],
              "status" => ["committed", "timeout_unknown"],
              "watermark_state" => ["verified"]
            },
            "known_fields" => [
              "commit_boundary",
              "durability",
              "operation_id",
              "status",
              "watermark_id",
              "watermark_state"
            ],
            "locality" => "shared",
            "required_fields" => [
              "commit_boundary",
              "durability",
              "operation_id",
              "status",
              "watermark_id",
              "watermark_state"
            ]
          }
        },
        "version" => "1"
      },
      "recovery" => %{
        "compatibility" => "additive",
        "types" => %{
          "continuity_mode" => %{
            "field_values" => %{
              "execution_authority" => ["none", "explicit_continuation_only", "read_only"],
              "mode" => ["exact", "transcript_only"],
              "ready" => [true, false]
            },
            "known_fields" => ["execution_authority", "mode", "ready", "watermark_id"],
            "locality" => "shared",
            "required_fields" => ["execution_authority", "mode", "ready", "watermark_id"]
          },
          "session_state" => %{
            "field_values" => %{
              "state" => [
                "loading",
                "claiming_generation",
                "verifying_history",
                "reconciling",
                "rebuilding",
                "exact_candidate",
                "transcript_candidate",
                "repair_required",
                "unavailable",
                "ready_exact",
                "ready_transcript_only"
              ]
            },
            "known_fields" => ["diagnostics", "generation", "state"],
            "locality" => "shared",
            "required_fields" => ["diagnostics", "generation", "state"]
          },
          "store_state" => %{
            "field_values" => %{
              "state" => [
                "validating_home",
                "recovering_maintenance",
                "migrating_store",
                "verifying_store",
                "store_ready",
                "unavailable"
              ]
            },
            "known_fields" => ["diagnostics", "schema_version", "state"],
            "locality" => "shared",
            "required_fields" => ["diagnostics", "schema_version", "state"]
          }
        },
        "version" => "1"
      },
      "rejection" => %{
        "compatibility" => "additive",
        "types" => %{
          "sensitive_result_blocked" => %{
            "field_values" => %{
              "phase" => ["final_boundary"],
              "surface" => [
                "provider_arguments",
                "provider_result",
                "tool_arguments",
                "tool_result"
              ]
            },
            "known_fields" => ["operation_id", "phase", "reason", "redacted_details", "surface"],
            "locality" => "shared",
            "max_encoded_bytes" => 65536,
            "required_fields" => [
              "operation_id",
              "phase",
              "reason",
              "redacted_details",
              "surface"
            ]
          },
          "sensitive_value_rejected" => %{
            "field_values" => %{
              "phase" => ["before_persistence"],
              "surface" => ["input", "command", "effect", "metadata", "error", "jidoka_value"]
            },
            "known_fields" => ["operation_id", "phase", "reason", "redacted_details", "surface"],
            "locality" => "shared",
            "max_encoded_bytes" => 65536,
            "required_fields" => [
              "operation_id",
              "phase",
              "reason",
              "redacted_details",
              "surface"
            ]
          }
        },
        "version" => "1"
      },
      "replay" => %{
        "compatibility" => "additive",
        "types" => %{
          "event_suffix" => %{
            "known_fields" => ["after_sequence", "events"],
            "locality" => "shared",
            "required_fields" => []
          },
          "replay_request" => %{
            "known_fields" => ["after_sequence", "client_id"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "response" => %{
        "compatibility" => "additive",
        "types" => %{
          "accepted" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "deferred" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          },
          "rejected" => %{
            "known_fields" => ["reason", "ref_id"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "snapshot" => %{
        "compatibility" => "additive",
        "types" => %{
          "session_snapshot" => %{
            "known_fields" => ["protocol_version", "sequence", "state"],
            "locality" => "shared",
            "required_fields" => []
          }
        },
        "version" => "1"
      },
      "watermark" => %{
        "compatibility" => "additive",
        "types" => %{
          "console_jidoka" => %{
            "field_values" => %{
              "state" => [
                "reserved",
                "jidoka_committed",
                "console_committed",
                "verified",
                "repair_required",
                "abandoned"
              ]
            },
            "known_fields" => [
              "console_chain_digest",
              "console_event_id",
              "console_sequence",
              "durable_schema_version",
              "generation",
              "jidoka_lease_id",
              "jidoka_request_id",
              "jidoka_revision",
              "jidoka_session_id",
              "jidoka_snapshot_id",
              "jidoka_value_digest",
              "protocol_version",
              "state",
              "watermark_id"
            ],
            "locality" => "shared",
            "required_fields" => [
              "console_chain_digest",
              "console_event_id",
              "console_sequence",
              "durable_schema_version",
              "generation",
              "jidoka_lease_id",
              "jidoka_request_id",
              "jidoka_revision",
              "jidoka_session_id",
              "jidoka_snapshot_id",
              "jidoka_value_digest",
              "protocol_version",
              "state",
              "watermark_id"
            ]
          }
        },
        "version" => "1"
      }
    },
    "protocol" => "jido.session",
    "sensitive_values" => %{
      "allowed_reference_fields" => [
        "credential_profile_id",
        "credential_reference_id",
        "credential_source_identity"
      ],
      "detail_limit_bytes" => 2048,
      "forbidden_field_names" => [
        "api_key",
        "authorization",
        "cookie",
        "credential",
        "credential_value",
        "password",
        "private_key",
        "secret",
        "secret_value",
        "token"
      ],
      "forbidden_shell_flags" => [
        "--api-key",
        "--authorization",
        "--cookie",
        "--credential",
        "--password",
        "--secret",
        "--token"
      ],
      "rejection_types" => ["sensitive_value_rejected", "sensitive_result_blocked"],
      "structural_string_fields" => [
        "arguments",
        "effective_arguments",
        "environment",
        "headers",
        "metadata",
        "uri",
        "url"
      ],
      "uri_fields" => ["uri", "url"],
      "version" => "1"
    },
    "version" => "1"
  }

  @doc "Returns the schema digest this file was generated from."
  @spec digest() :: String.t()
  def digest, do: @digest

  @doc "Returns the generated protocol catalog."
  @spec catalog() :: map()
  def catalog, do: @catalog

  @doc "Returns generated family names."
  @spec families() :: [String.t()]
  def families, do: Map.keys(@catalog["families"]) |> Enum.sort()

  @doc "Returns generated type names for one family."
  @spec types(String.t()) :: [String.t()]
  def types(family) when is_binary(family) do
    @catalog
    |> get_in(["families", family, "types"])
    |> List.wrap()
    |> then(fn
      [types] when is_map(types) -> Map.keys(types) |> Enum.sort()
      _other -> []
    end)
  end
end
