defmodule Jido.Console.Session.Protocol.Generator do
  @moduledoc """
  Writes generated Elixir and TypeScript protocol types from the canonical schema.
  """

  alias Jido.Console.Session.Protocol

  @elixir_path "lib/jido_console/session/protocol/generated.ex"
  @typescript_path "priv/session/protocol/generated.ts"

  @type paths :: %{elixir: Path.t(), typescript: Path.t(), digest: String.t()}

  @doc "Returns the SHA-256 digest of the canonical schema file."
  @spec digest(Path.t()) :: String.t()
  def digest(path \\ Protocol.schema_path()) do
    path
    |> File.read!()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  @doc "Writes generated Elixir and TypeScript files."
  @spec write!(map(), keyword()) :: paths()
  def write!(schema, opts \\ []) do
    root = Keyword.get_lazy(opts, :root, &File.cwd!/0)
    digest = digest(Keyword.get(opts, :schema_path, Protocol.schema_path()))
    catalog = catalog(schema, digest)
    elixir = Path.join(root, @elixir_path)
    typescript = Path.join(root, @typescript_path)

    File.mkdir_p!(Path.dirname(elixir))
    File.mkdir_p!(Path.dirname(typescript))

    formatted_elixir =
      catalog
      |> elixir_source()
      |> Code.format_string!()
      |> IO.iodata_to_binary()
      |> String.trim_trailing()

    File.write!(elixir, formatted_elixir <> "\n")
    File.write!(typescript, typescript_source(catalog))
    %{elixir: elixir, typescript: typescript, digest: digest}
  end

  @doc "Builds the portable generated catalog."
  @spec catalog(map(), String.t()) :: map()
  def catalog(schema, digest) do
    families =
      Map.new(Protocol.families(), fn family ->
        {:ok, types} = Protocol.types(schema, family)
        {:ok, compatibility} = Protocol.compatibility(schema, family)
        family_declaration = get_in(schema, ["families", family])

        declarations =
          Map.new(types, fn name ->
            {:ok, declaration} = Protocol.type(schema, family, name)
            {name, normalize_declaration(family_declaration, declaration)}
          end)

        {family, Map.merge(compatibility, %{"types" => declarations})}
      end)

    {:ok, bounds} = Protocol.bounds(schema)
    {:ok, authority} = Protocol.authority(schema)
    {:ok, identity} = Protocol.identity(schema)

    %{
      "protocol" => identity.protocol,
      "version" => identity.version,
      "digest" => digest,
      "families" => families,
      "bounds" => bounds,
      "authority" => authority,
      "client_local_fields" => Protocol.client_local_fields(schema)
    }
  end

  defp normalize_declaration(family, declaration) do
    required_fields = unique_fields(List.wrap(family["required"]) ++ List.wrap(declaration["required"]))

    known_fields =
      unique_fields(
        List.wrap(family["fields"]) ++
          required_fields ++
          List.wrap(declaration["fields"])
      )

    %{
      "required_fields" => required_fields,
      "known_fields" => known_fields,
      "locality" => declaration["locality"]
    }
    |> maybe_put("deprecated", declaration["deprecated"])
    |> maybe_put("emission", declaration["emission"])
  end

  defp unique_fields(fields) do
    fields
    |> Enum.uniq()
    |> Enum.sort()
  end

  defp elixir_source(catalog) do
    """
    defmodule Jido.Console.Session.Protocol.Generated do
      @moduledoc \"""
      Generated protocol types for `jido.session` v#{catalog["version"]}.

      Do not edit this file. Run `mix jido.protocol.generate`.
      \"""

      @digest #{inspect(catalog["digest"])}
      @catalog #{inspect(catalog, limit: :infinity, printable_limit: :infinity)}

      @doc "Returns the schema digest this file was generated from."
      @spec digest() :: String.t()
      def digest, do: @digest

      @doc "Returns the generated protocol catalog."
      @spec catalog() :: map()
      def catalog, do: @catalog

      @doc "Returns generated family names."
      @spec families() :: [String.t()]
      def families, do: Map.keys(@catalog["families"]) |> Enum.sort()

      @doc "Returns generated type names for one family."
      @spec types(String.t()) :: [String.t()]
      def types(family) when is_binary(family) do
        @catalog
        |> get_in(["families", family, "types"])
        |> List.wrap()
        |> then(fn
          [types] when is_map(types) -> Map.keys(types) |> Enum.sort()
          _other -> []
        end)
      end
    end
    """
  end

  defp typescript_source(catalog) do
    family_unions =
      catalog["families"]
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map_join("\n", fn {family, entry} ->
        types = entry["types"] |> Map.keys() |> Enum.sort() |> Enum.map_join(" | ", &inspect/1)
        "export type #{ts_name(family)}Type = #{types};"
      end)

    family_envelopes =
      catalog["families"]
      |> Enum.sort_by(&elem(&1, 0))
      |> Enum.map_join("\n\n", fn {family, entry} ->
        envelope_names =
          entry["types"]
          |> Enum.sort_by(&elem(&1, 0))
          |> Enum.map(fn {type, contract} ->
            name = "#{ts_name(family)}#{ts_name(type)}Envelope"

            payload_fields = render_payload_fields(contract)

            deprecation =
              if contract["deprecated"] do
                "\n/** @deprecated #{contract["emission"] || "compatibility only"} */"
              else
                ""
              end

            declaration = """
            #{deprecation}
            export interface #{name} extends ProtocolEnvelopeBase {
              family: #{inspect(family)};
              type: #{inspect(type)};
              payload: {
            #{payload_fields}
              };
            }
            """

            {name, declaration}
          end)

        union = Enum.map_join(envelope_names, " | ", &elem(&1, 0))
        declarations = envelope_names |> Enum.map_join("\n", &elem(&1, 1))

        "#{declarations}\nexport type #{ts_name(family)}Envelope = #{union};"
      end)

    protocol_envelopes =
      catalog["families"]
      |> Map.keys()
      |> Enum.sort()
      |> Enum.map_join(" | ", &"#{ts_name(&1)}Envelope")

    """
    /* Generated protocol types for jido.session v#{catalog["version"]}. */
    /* Do not edit this file. Run mix jido.protocol.generate. */

    export const protocolDigest = #{inspect(catalog["digest"])};
    export const protocolName = #{inspect(catalog["protocol"])};
    export const protocolVersion = #{inspect(catalog["version"])};
    export const protocolBounds = #{Jason.encode!(catalog["bounds"])} as const;
    export const protocolAuthority = #{Jason.encode!(catalog["authority"])} as const;
    export const clientLocalFields = #{Jason.encode!(catalog["client_local_fields"])} as const;
    export const protocolFamilies = #{Jason.encode!(catalog["families"])} as const;

    #{family_unions}

    export type ProtocolFamily = #{catalog["families"] |> Map.keys() |> Enum.sort() |> Enum.map_join(" | ", &inspect/1)};

    export interface ProtocolEnvelopeBase {
      protocol: #{inspect(catalog["protocol"])};
      version: string;
      id: string;
      session_id?: string;
      created_at?: string;
    }

    #{family_envelopes}

    export type ProtocolEnvelope = #{protocol_envelopes};

    export function knownType(family: string, type: string): boolean {
      const entry = (protocolFamilies as Record<string, { types: Record<string, unknown> }>)[family];
      return Boolean(entry && entry.types && type in entry.types);
    }
    """
  end

  defp render_payload_fields(contract) do
    contract["known_fields"]
    |> Enum.map_join("\n", fn field ->
      optional = if field in contract["required_fields"], do: "", else: "?"
      "    #{inspect(field)}#{optional}: unknown;"
    end)
  end

  defp ts_name(family) do
    family
    |> String.split("_")
    |> Enum.map_join("", &String.capitalize/1)
  end

  defp maybe_put(map, _key, nil), do: map
  defp maybe_put(map, key, value), do: Map.put(map, key, value)
end
