name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  ci:
    name: CI
    uses: agentjido/github-actions/.github/workflows/jido-ci.yml@c782c2d13584f0a7b43027eedd83807ed1a2b7dc # v5
    with:
      docs_command: mix docs
      test_command: mix coveralls --exclude darwin --exclude expect --exclude flaky
      credo_command: mix credo
      validate_hex_package: false
